pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/051821/Recommender-sys.git'
        BRANCH = 'main'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: "${BRANCH}", url: "${REPO_URL}"
            }
        }

        stage('Verify Docker Compose File') {
            steps {
                // List contents of the 'app' directory to verify the presence of Docker-compose.yml
                bat 'dir C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\Recommender-sys\\app'
            }
        }

        stage('Build Docker Images') {
            steps {
                bat 'docker-compose -f app/Docker-compose.yml build'
            }
        }

        stage('Run Containers') {
            steps {
                bat 'docker-compose -f app/Docker-compose.yml up -d'
            }
        }

        stage('Check Running Containers') {
            steps {
                bat 'docker ps'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished!'
        }
    }
}